[project]
name = "tilde"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyinfra>=3.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
